# Generated by Django 6.0.4 on 2026-05-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('unit', models.CharField(choices=[('PCS', 'kawałków'), ('SLI', 'plasterków'), ('BTL', 'butelki'), ('CAP', 'kapsułek'), ('CRT', 'kartonu')], default='PCS', max_length=3)),
                ('minimum_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
